# LibreLane configuration file

DESIGN_NAME: heichips25_fazyrv_exotiny
VERILOG_FILES:
  - dir::../build/exotiny_preproc.v
  - dir::../src/heichips25_fazyrv_exotiny.sv
  - dir::logo/rtl/fazyrv_small_logo.v

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# This should not be needed
#FP_OBSTRUCTIONS:
#- [410, 10, 462.5, 60]

ROUTING_OBSTRUCTIONS:
 - [Metal5, 410, 10, 462.5, 60]

# Small DEF template
#DIE_AREA: [0, 0, 500, 200]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
DIE_AREA: [0, 0, 500, 415]
FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true

#PDN_OBSTRUCTIONS:
# - [TopMetal1, 435, 5, 495, 65]
