
logo:
	python3 make_gds.py --cellname fazyrv_small_logo --scale 1.0 --pixel-size 0.5 --threshold 128 --layer 126 --datatype 0 --invert --merge fazyrv_small.png gds/fazyrv_small_logo.gds

.PHONY: logo